### ISSUE TITLE
Mod の形態について

### ISSUE THREAD

**Issue by QuartzMiner** [ccserver-modder/homunculus#1]
## 機能一覧
- 最初から最後まで独自のModとして作ってもよし
- or ComputerCraft の外部機器として動作
- 周囲の entity を操る程度の能力
- 独自 entity "homunculus" を追加？

**Comment by Azure0rigin** [comment]
こんなん考えた（そもそも可能かどうかすら判らないのですが）

MinecraftのMob追加Mod  
プログラミング言語Luaによって行動を規定可能  
現在、LMMライクなベーシックモード、CCライクなヒューマノイドモード、プレイヤーの再現を目指すマルチプレイヤーモードの実装を予定（と書いて妄想と読む）（プログラムできる気がしない）

| 項目 | 進捗 (%) |
| --- | --- |
| アルゴリズム理論構築 | □□□□□□□□□□□□□□□□□□□□　0% |
| モデリング | □□□□□□□□□□□□□□□□□□□□　0% |
| AIコーディング | □□□□□□□□□□□□□□□□□□□□　0% |
| Modding予習 | ■□□□□□□□□□□□□□□□□□□□　3% (かじったか？　程度) |
| Java | ■□□□□□□□□□□□□□□□□□□□　2% (エラーログを見て目を回さない程度) |
| Lua | ■□□□□□□□□□□□□□□□□□□□　5% (スパゲッティメーカー) |

---
- 要求性能  
  - -.H.Mプレイヤーインベントリの常時監視  
  - B.H.M.アイテムの属性データ、重要度データの管理  
  - B.H.M.マルチターゲット戦闘能力  
- いろいろ  
  - モデルの関節部分に面を張って切れ目を無くしたい  
  - LMMモデル使用可能にしたい  
  - 経路探索アルゴリズムの強化（空堀くらいは飛び越えてほしい）  
  - 地形や他Modのブロックによるエリアの登録（エンダーマンと対峙するときに屋根のある所に逃げ込んでみたり）  
  - 金リンゴを積んでHP回復/秒アップとか実装してみたい
