### ISSUE TITLE
homunculusの召喚方法について

### ISSUE THREAD

**Issue by Azure0rigin** [ccserver-modder/homunculus#6]
ホムンクルスは自然スポーンするものではない、という前提の上で召喚方法について決めましょう。  

方法としては  
- スポーンエッグ、およびそのクラフトレシピの追加  
- 召喚用アイテムの追加  
- ゴーレムのようなマルチブロック構造体によるスポーン  
- コマンドによる召喚  
- その他  

のいずれか、もしくは複数となる訳ですが。  

個人的にはArsMagicaのボス召喚のような「ブロック＋アイテム」の形で培養槽ちっくなものでも建てるか  
もしくはパラケルススに倣ってガラス瓶に関連した何かを用意するくらいが妥当かなと思っています

**Comment by QuartzMiner** [comment]
まず召喚用アイテム＋構造物でやってみます。
